spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Manasa@1998
    url: jdbc:mysql://localhost:3306/PatientData
    username: root
  application:
    name: patient-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
springdoc:
 swagger-ui:
  path:swagger-ui.html
 